name: getxcli
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  logger: ^1.1.0 
  get: ^4.6.6
  cupertino_icons: ^1.0.8
  flutter_contacts: ^1.1.7+1 # Vérifie la version la plus récente sur pub.dev
  permission_handler: ^10.0.0
  dio: ^5.0.0
  flutter_secure_storage: ^9.2.2
  flutter_riverpod: ^2.0.0
  intl: ^0.17.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_database: ^10.3.8  
  google_sign_in: ^6.1.0
  qr_flutter: ^4.1.0
  mobile_scanner: ^3.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.9.2
  http: ^1.2.2

flutter:
  uses-material-design: true
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"